### ISSUE TITLE
Mint-X

### ISSUE THREAD

**Issue by freonheat** [the-allanc/minty-color-titles#1]
Thanks so much for this.  It is amazing to me that Mint hasn't addressed these issues.  Although it works great with Mint-Y, Mint-Y doesn't do what I want because the buttons have no different background and blend into everything else.  Mint-X does meet my needs, but your css doesn't really do much with Mint-X except change the buttons.  Is there any chance something like your code could be modified to work with Mint-X to change the titlebar focus background?

**Comment by the-allanc** [comment]
I haven't got Mint 21 installed locally (yet), so I had to boot it off a USB stick - but once there, turns out that the file didn't need too much tweaking to get it doing the right thing for Mint-X - just had to figure out what was preventing the header bars from being colored. You can find it in the repository.

Also made tweaks so apps like Calculator wouldn't use a shadow that made the text and icons appear blurry. Hope that works for you.

**Comment by freonheat** [comment]
OMG, it works with Mint-X themes now!  Great!   Funny how such little things can make such a big difference.

Thanks so much!

**Comment by nairdesigns** [comment]
Not a question or anything, just want to say you're extremely awesome for this. was looking for this solution for about 3 weeks now. Makes the windows so much easier to see! Thank you!!
